/* Meshtastic Rust Library FFI Bindings */
/* Auto-generated by cbindgen - DO NOT EDIT */

#ifndef MESHTASTIC_RUST_H
#define MESHTASTIC_RUST_H

/* Generated with cbindgen:0.27.0 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Example function that can be called from C++
 * Returns a greeting message
 */
const char *rust_hello(void);

/**
 * Free a string allocated by Rust
 */
void rust_free_string(char *s);

/**
 * Example computation function
 */
int32_t rust_add(int32_t a, int32_t b);

#endif  /* MESHTASTIC_RUST_H */
